baseURL = "https://nafiasib.github.io/intro/"
languageCode = "en-us"
publishDir = "docs"
title = "!"
theme = "hallo"
[Author]
    name = "Nafi Asib"
[params]
    greeting = "Hi! I'm K. M. Nafi Asib"
    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://facebook.com/nafi.asib"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/NafiAsib"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "Mail Me!"
        url = "mailto:nafi.asib@gmail.com"